PieWorkShop/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using PieWorkShop.Models;

namespace PieWorkShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository pieRepository;
        public PieController(IPieRepository pieRepository)
        {
            this.pieRepository = pieRepository;
        }

        public ViewResult List()
        {
            var pies = pieRepository.AllPies;
            return View(pies);
        }
    }
}

PieWorkShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Work Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PieWorkShop.styles.css" asp-append-version="true" />
</head>
<body style="background-image: url(/Images/bg.jpg);">

    <div class="container">

         <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
             <span class="logo"> <a asp-controller="Home" asp-action="Index"><img src="~/Images/GL-logo.png" alt="" width="50" height="40" class="d-inline-block align-text-top"></a> </span>
          <a class="navbar-brand" asp-controller="Home" asp-action="Index">Home</a>
          <a class="navbar-brand" asp-controller="Home" asp-action="Privacy">Privacy</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link navbar-brand" asp-controller="Student" asp-action="List">Students</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="TeamA" asp-action="ListA"> Team A </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="TeamB" asp-action="ListB"> Team B </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="TeamC" asp-action="ListC"> Team C </a>
              </li>
                 <li class="nav-item">
                <a class="nav-link" asp-controller="TeamD" asp-action="ListD"> Team D </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Student" asp-action="ListMale"> Male </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Student" asp-action="ListFemale"> Female </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Student" asp-action="ListSName"> Name S</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Student" asp-action="ListSpoc"> SPOC </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-controller="Pie" asp-action="List"> Have Some Pie </a>
              </li>
              <li class="nav-item">
                  <partial name="_LoginPartial">
              </li>
            </ul>
          </div>
    </nav>

        <div class="row">
            <main role="main" class="pb-3">
                @RenderBody()
                @*actual content is fetched and places here*@
            </main>
        </div>

    </div>

    <footer class="border-top footer text-muted bg-light ">
        <div class="container-lg">
            &copy; 2022 - Umeed - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PieWorkShop/Views/Shared/_StudentTPartial.cshtml
@using PieWorkShop.ViewModels
@model CustomClass

@*Partial View avoid repeatable code
Inside Shared folder as _FileName.cshtml*@

<html>
    <p>
        Total Student(s): @Model.count
        <br>
        Add new student(s): <a asp-controller="Student" asp-action="Create">click here</a> 
    </p>
    
    <body>
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th scope="col">First Name</th>
              <th scope="col">Last Name</th>
              <th scope="col">Email</th>
              <th scope="col">Age</th>
              <th scope="col">Gender</th>
              <th scope="col">Team</th>
              <th scope="col">Action</th>
             
            </tr>
          </thead>
            <tbody>
            @foreach(var student in Model.students)
            {
                <tr>
                    <td><a asp-controller="Student" asp-action="Details" asp-route-id1="@student.StudentID">@student.FirstName</a></td>
                    <td>@student.LastName</td>
                    <td>@student.EmailId</td>
                    <td>@student.Age </td>
                    <td>@student.Gender</td>
                    <td>@student.TeamName </td>
                    <td><a asp-controller="Student" asp-action="Remove" asp-route-id3="@student.StudentID">Remove</a></td>
                </tr>                  

            }  
            </tbody>
        </table>       
    </body>
</html>